author: Diarios de Zacatecas 
twitter: twitter.com/ljz
github: github.com/ljzac
prose:
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Título"
          placeholder: "Escriba el título de la nota"
          value: ""
      - name: "twitt"
        field:
          element: "text"
          label: "Balazo"
          placeholder: "El balazo o sumario de la nota"
          value: "" 
      - name: "author"
        field:
          element: "text"
          label: "Autor"
          placeholder: "Autor de la nota con abreviatura (ej. pphdez)"
          value: "" 
      - name: "authorlink"
        field:
          element: "text"
          label: "Página del Autor"
          placeholder: "Página del Autor"
          value: ""
      - name: "location"
        field:
          element: "select"
          label: "Ubicación"
          placeholder: "Selecciona una ubicación"
          options:
            - name: "Local"
              value: "Local"
            - name: "Nacional"
              value: "Nacional"
            - name: "Internacional"
              value: "Internacional"
          selected: "Local"
      - name: "category"
        field:
          element: "select"
          label: "Sección"
          placeholder: "Selecciona una sección"
          options:
            - name: "Portada"
              value: "Portada"
            - name: "Ciencia y Tecnología"
              value: "Ciencia y Tecnología"
            - name: "Cultura y Espectáculos"
              value: "Cultura y Espectáculos"
            - name: "Opinión"
              value: "Opinión"
            - name: "Educación"
              value: "Educación"
            - name: "Elecciones 2013"
              value: "Elecciones 2013"
            - name: "Sociedad y Justicia"
              value: "Sociedad y Justicia"
            - name: "Contraportada"
              value: "Contraportada"
            - name: "Deportes"
              value: "Deportes"
            - name: "Política"
              value: "Política"
            - name: "Economía"
              value: "Economía"
            - name: "Mundo"
              value: "Mundo"
            - name: "Municipios"
              value: "Municipios"
            - name: "Reportaje Especial"
              value: "Reportaje Especial"
            - name: "De Rock"
              value: "De Rock"
            - name: "La Jiribilla"
              value: "La Jiribilla"
            - name: "Fuera de Foco"
              value: "Fuera de Foco"
            - name: "Cartones"
              value: "Cartones"
            - name: "Principales"
              value: "Principales"
            - name: "Zona de Reflexión"
              value: "Zona de Reflexión"
            - name: "México"
              value: "México"
            - name: "Destacadas"
              value: "Destacadas"
            - name: "Autor"
              value: "Autor"
            - name: "Publicidad"
              value: "Publicidad"
            - name: "Editorial"
              value: "Editorial"
            - name: "Memoria"
              value: "Memoria"
            - name: "Editorial Blog"
              value: "Editorial Blog"  
          selected: "Portada" 
      - name: "layout"
        field:
          element: "select"
          label: "layout"
          placeholder: "Selecciona un layout"
          options:
            - name: "posts"
              value: "posts"
          selected: "posts"

minutebyminute: ['Autor', 'Publicidad']
